aclrules:
  allow icmp:
    ispermit: 1
    srcprefix:
      address:
        af: 0
        un:
          xxx_uniondata:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
      len: 0
    dstprefix:
      address:
        af: 0
        un:
          xxx_uniondata:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
      len: 0
    proto: 1
    srcportoricmptypefirst: 0
    srcportoricmptypelast: 65535
    dstportoricmpcodefirst: 0
    dstportoricmpcodelast: 65535
    tcpflagsmask: 0
    tcpflagsvalue: 0
  allow tcp8080:
    ispermit: 1
    srcprefix:
      address:
        af: 0
        un:
          xxx_uniondata:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
      len: 0
    dstprefix:
      address:
        af: 0
        un:
          xxx_uniondata:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
      len: 0
    proto: 6
    srcportoricmptypefirst: 0
    srcportoricmptypelast: 65535
    dstportoricmpcodefirst: 8080
    dstportoricmpcodelast: 8080
    tcpflagsmask: 0
    tcpflagsvalue: 0
